[project]
name = "pac-mac"
version = "1.0.0"
description = """
    Recreate the famous arcade game Pac-Man with a modern Python codebase,
    a clean project structure, and a deployable build.
    """

readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flake8>=7.3.0",
    "mazegenerator",
    "mypy>=2.3.0",
    "pygame-ce>=2.5.7",
]

[tool.uv.sources]
mazegenerator = { path = "lib/mazegenerator-2.1.0-py3-none-any.whl" }
