[project]
name = "pac-mac"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "mazegenerator",
    "pygame-ce>=2.5.7",
]

[tool.uv.sources]
mazegenerator = { path = "mazegenerator-00001/mazegenerator-2.1.0-py3-none-any.whl" }
